# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  maplrapi:
    image: maplr_api
    ports:
      - 8080:8080
  
  tests:
    image: maplr_api_tests
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    command: [
      "dotnet",
      "test",
      "TestMaplrSugarShack.dll",
      ]
    depends_on:
      - maplrapi