version: '3.4'

services:
  maplr-api:
    image: maplr_api
    ports:
      - 8080:8080
    build:
      context: .
      target: final
  
  maplr-api-tests:
    image: maplr_api_tests
    build:
      context: .
      target: testrunner
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    command: [
      "dotnet",
      "test",
      "maplr-api-tests.dll",
      ]
    depends_on:
      - maplr-api