# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
# https://code.visualstudio.com/docs/containers/quickstart-aspnet-core

version: '3.4'

services:
  maplrapi:
    image: maplrapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5099:5099
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
